# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'aircast-demo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for aircast-demo
  pod 'aircast', :git => 'https://github.com/AirCastLab/aircast-ios.git'
end
